modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[[mods]]
    modId="candycraft_rebaked"
    version="${file.jarVersion}"
    displayName="Candycraft-Rebaked"
    updateJSONURL="http://myurl.me/"
    displayURL="http://example.com/"
    logoFile="missingno.png"
    credits="Some peeps who like minecraft and sweets"
    authors="Lord Evo and his dedicated and hardworking diciples"
    description="We really like sugar."

[[dependencies.candycraft_rebaked]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.candycraft_rebaked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.candycraft_rebaked]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[x.x.x,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.candycraft_rebaked]]
    modId="neapolitan"
    mandatory=true
    versionRange="[x.x.x,)"
    ordering="AFTER"
    side="BOTH"
